version: 2
jobs:
  build:
    working_directory: ~/wabi
    docker:
      - image: circleci/ruby:2.7.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rspec
      - run: bundle exec rubocop
